main: aliuly\itemcasepe\Main
api: [4.0.0]
load: POSTWORLD

name: ItemCasePE
description: An implementation of Bukkit's ItemCase
version: 1.2.6
author: aliuly

commands:
  itemcase:
    description: ItemCase management command
    usage: "/itemcase [add|cancel|respawn]"
    aliases: [ic]
    permission: itemcase.cmd

permissions:
 itemcase:
  default: false
  description: "allow players access to all itemcase features"
  children:
   itemcase.cmd:
    default: op
    description: "allow players access to the itemcase command"
   itemcase.destroy:
    default: op
    description: "allow players to destroy cases"
